version: '3.8'

x-airflow-common:
  &airflow-common
  build: ./airflow
  env_file:
    - .env
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__CORE__SQL_ALCHEMY_CONN}
    - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=False
    - AIRFLOW__WEBSERVER__SECRET_KEY=${AIRFLOW__WEBSERVER__SECRET_KEY}
    - AIRFLOW_CONN_ODS_POSTGRES=${AIRFLOW_CONN_ODS_POSTGRES}
    - AIRFLOW_CONN_MINIO_CONN=${AIRFLOW_CONN_MINIO_CONN}
    - AIRFLOW_CONN_MINIO_CONN__EXTRA=${AIRFLOW_CONN_MINIO_CONN__EXTRA}
    - AIRFLOW_CONN_ODS_MONGO=${AIRFLOW_CONN_ODS_MONGO}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./sql:/opt/airflow/sql
  depends_on:
    - airflow_postgres
  networks:
    - airflow_net

services:
  airflow_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    networks:
      - airflow_net
    ports:
      - "5433:5432"

  airflow-init:
    <<: *airflow-common
    entrypoint: ["/opt/airflow/init.sh"]
    volumes:
      - ./airflow/init.sh:/opt/airflow/init.sh
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  ods_postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${ODS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${ODS_POSTGRES_PASSWORD}
      POSTGRES_DB: ${ODS_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - ods_pgdata:/var/lib/postgresql/data
    networks:
      - airflow_net

  pgadmin:
    image: dpage/pgadmin4:8.12
    depends_on:
      ods_postgres:
        condition: service_started
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"

  pg-superset:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - pg_superset_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "superset" ]
      interval: 5s
      retries: 10

  superset:
    build: ./superset
    depends_on:
      pg-superset:
        condition: service_healthy
    environment:
      SUPERSET_SECRET_KEY: "THIS_IS_A_TEMPORARY_SECRET_KEY_REPLACE_IN_PROD"
      SQLALCHEMY_DATABASE_URI: "postgresql://superset:superset@pg-superset:5432/superset"
      SUPERSET_LOAD_EXAMPLES: "no"
      ODS_POSTGRES_PASSWORD: ${ODS_POSTGRES_PASSWORD}
    ports:
      - "8088:8088"
    volumes:
      - superset_home:/app/superset_home
      - ./superset/init.sh:/app/init.sh
      - ./superset/superset_data.zip:/app/superset_data.zip
    entrypoint: [ "/bin/bash", "/app/init.sh" ]
    networks:
      airflow_net:

networks:
  airflow_net:

volumes:
  postgres_airflow_data:
  ods_pgdata:
  pg_superset_data:
  superset_home:
